export enum LocalStorageEnum {
  FavoriteId = 'favoriteId',
  FavoriteId2023 = 'favoriteId2023',
  Language = 'language',
  BeepleId = 'beepleId',
  BeepleToken = 'beepleToken',
  BeepleEmail= 'beepleEmail',
  AvoidNotification = 'avoidNotification',
  OfflineShifts = 'offlineShifts',
  OfflineFavorites = 'offlineFavorites',
  OfflineProgrammes = 'offlineProgrammes',
  OfflineDays = 'offlineDays',
  SellerDepartment = 'sellerDepartment',
  SellerPostalCode = 'sellerPostalCode',
  SellerSellingGoal = 'sellerSellingGoal',
  VolunteerName = 'volunteerName',
  SellerName = 'sellerName',
  SellerEmail = 'sellerEmail',
  SellerFromWorkGroup = 'sellerFromWorkGroup',
  SellingTmp = 'sellingTmp',
  KnowNotNFC = 'KnowNotNFC',
  KnowPayconic= 'KnowPayconic',
}